### ISSUE TITLE
FritzOS 6.XX doesn't respont with a valid SID

### ISSUE THREAD

**Issue by petersbruder** [schuppeste/Arduino-Fritzbox-Login#1]
Hello, your sketch works perfect, but one thing: The current FritzOS doesn't allow capitals in the response string.
I've removed the line with the UPPERCHAR function. And it worked :-)
Hallo, dein Sketch läuft super. Aber das aktuelle FritzOS erlaubt keine GROSSBUCHSTABEN in dm Response String. Ich habe die UPPERCHAR Zeile gelöscht. UNd schwupps: Alles Funktioniert

**Comment by schuppeste** [comment]
Danke für den Hinweis, ich werde das ändern.

Thanks, changed.
